// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iklhgukbjtcuqdptgxfg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlrbGhndWtianRjdXFkcHRneGZnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwMDU0NTEsImV4cCI6MjA2NTU4MTQ1MX0.owcO9DWc90GvgIi1fVDlXCGhEX0OZ2MPzH33yV0Jx8I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);