// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sbvwrlbgboosazyclsbz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNidndybGJnYm9vc2F6eWNsc2J6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAxNTQ5MTAsImV4cCI6MjA2NTczMDkxMH0.Kwf68Q61wLdVQXhRtRK6lmafsERLLCAvsxarxoXZ2XI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);